-- ユーザーの作成
CREATE USER MySchema IDENTIFIED BY "MySchema"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS
/
GRANT CONNECT TO MySchema
/
GRANT DBA TO MySchema
/
GRANT RESOURCE TO MySchema
/
GRANT DROP ANY TABLE TO MySchema
/
GRANT UNLIMITED TABLESPACE TO MySchema
/
GRANT READ,WRITE ON DIRECTORY DATA_PUMP_DIR TO MySchema
/
exit